import { sqliteTable, text, primaryKey } from "drizzle-orm/sqlite-core";

/**
 * Tracks which derived notifications each employee has read.
 *
 * Notifications are derived at query time (not stored), so read state is the
 * only thing that needs persistence. The notificationKey is a content-aware
 * key generated by the resolver — aggregate notifications encode meaningful
 * state (e.g. "admin-hr-queue:5") so that a count change produces a new key,
 * making the notification unread again automatically.
 */
export const notificationReads = sqliteTable(
  "notification_reads",
  {
    employeeId: text("employee_id").notNull(),
    notificationKey: text("notification_key").notNull(),
    readAt: text("read_at").notNull(),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.employeeId, table.notificationKey] }),
  }),
);

export type NotificationRead = typeof notificationReads.$inferSelect;
export type NewNotificationRead = typeof notificationReads.$inferInsert;
